// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZBm7rNRvT8T7YZPw2o4j-sh5hEjeBOzU',
    appId: '1:146466571790:web:32574275b95fe1057e9e5f',
    messagingSenderId: '146466571790',
    projectId: 'inifap-33d69',
    authDomain: 'inifap-33d69.firebaseapp.com',
    storageBucket: 'inifap-33d69.firebasestorage.app',
    measurementId: 'G-Z4GXT18LK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkGqlJvQfJXuaWydIN-EOmS8AluFzXeKc',
    appId: '1:146466571790:android:d254c95239e2943f7e9e5f',
    messagingSenderId: '146466571790',
    projectId: 'inifap-33d69',
    storageBucket: 'inifap-33d69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDCSuW2OWsYvSJCNpWmgHyIX2inOkV2AE',
    appId: '1:146466571790:ios:86aa84106d6267777e9e5f',
    messagingSenderId: '146466571790',
    projectId: 'inifap-33d69',
    storageBucket: 'inifap-33d69.firebasestorage.app',
    iosBundleId: 'com.example.clima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDCSuW2OWsYvSJCNpWmgHyIX2inOkV2AE',
    appId: '1:146466571790:ios:86aa84106d6267777e9e5f',
    messagingSenderId: '146466571790',
    projectId: 'inifap-33d69',
    storageBucket: 'inifap-33d69.firebasestorage.app',
    iosBundleId: 'com.example.clima',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZBm7rNRvT8T7YZPw2o4j-sh5hEjeBOzU',
    appId: '1:146466571790:web:c077886ef9eec21a7e9e5f',
    messagingSenderId: '146466571790',
    projectId: 'inifap-33d69',
    authDomain: 'inifap-33d69.firebaseapp.com',
    storageBucket: 'inifap-33d69.firebasestorage.app',
    measurementId: 'G-JGV7FVF8NQ',
  );
}
